# Generated by Django 3.1.4 on 2021-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210516_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selled',
            field=models.IntegerField(default=0, verbose_name='Продано товаров'),
        ),
    ]
