# Generated by Django 3.1.4 on 2021-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lease',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
