# Generated by Django 3.1.4 on 2021-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210526_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CAR', 'Картой'), ('CAS', 'Наличными')], default='CAR', max_length=3, null=True),
        ),
    ]
