# Generated by Django 3.1.4 on 2021-05-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('cart',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
